### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by guettli** [jfmatth/DjangoOnKubernetes#10]
Hi,

there are not many tutorials which explain how to set up Django for K8s.

I am interested in updates, or point to a better guide, if you know a better one.

Thank you.

**Comment by jfmatth** [comment]
HI @guettli thanks for the notice.

I put this together a while ago when i was moving my django app to K8s, and tried to finish it.

You're right, there aren't many and honestly, after doing it, it's pretty easy.

are there areas you're having trouble, happy to help.

feel free to put PR's on this one so we'll improve it for others :)
